shared:
    settings:
        email:
            addresses: [moloch.build@oath.com]
            statuses: [SUCCESS, FAILURE]
jobs:
    centos-6:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-6:0.20.2
        steps:
            - ln -s /thirdparty .
            - build: scl enable devtoolset-3 "./easybutton-build.sh"
            - export PATH=/data/moloch/bin:$PATH
            - installing: scl enable devtoolset-3 "make install"
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - test-capture: (cd tests ; ./tests.pl)
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js | tr "-" "_"`
                if [ "$GIT_BRANCH" = "origin/master" ]; then
                  scl enable ruby193 "/opt/rh/ruby193/root/usr/local/bin/fpm -s dir -t rpm -n moloch -v $MOLOCH_VERSION --iteration $SD_BUILD_ID --template-scripts --after-install 'release/afterinstall.sh' --url "http://molo.ch" --description 'Moloch Full Packet System' -d perl-libwww-perl -d perl-JSON -d ethtool -d libyaml-devel /data/moloch"
                  scl enable python27 "aws s3 cp --quiet moloch*.x86_64.rpm s3://files.molo.ch/moloch-master.centos6.x86_64.rpm --acl public-read"
                  scl enable python27 "aws s3api put-object-acl --bucket files.molo.ch --key moloch-master.centos6.x86_64.rpm --acl public-read"
                fi
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

# Centos 7 is the only build to have test-ui because installing chrome dependancies sucks
    centos-7:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-7:0.20.2
        steps:
            - ln -s /thirdparty .
            - build: ./easybutton-build.sh
            - export PATH=/data/moloch/bin:$PATH
            - installing: make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - test-capture: (cd tests ; ./tests.pl)
            - export TZ=US/Eastern
            - test-ui: (cd viewer; npm install ; npm test)
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js | tr "-" "_"`
                if [ "$GIT_BRANCH" = "origin/master" ]; then
                  fpm -s dir -t rpm -n moloch -v $MOLOCH_VERSION --iteration $SD_BUILD_ID --template-scripts --after-install "release/afterinstall.sh" --url "http://molo.ch" --description "Moloch Full Packet System" -d perl-libwww-perl -d perl-JSON -d ethtool -d libyaml-devel /data/moloch
                  aws s3 cp --quiet moloch*.x86_64.rpm s3://files.molo.ch/moloch-master.centos7.x86_64.rpm --acl public-read
                  aws s3api put-object-acl --bucket files.molo.ch --key moloch-master.centos7.x86_64.rpm --acl public-read
                fi
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

    ubuntu-14:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-14:0.20.2
        steps:
            - ln -s /thirdparty .
            - build: ./easybutton-build.sh
            - export PATH=/data/moloch/bin:$PATH
            - installing: make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - test-capture: (cd tests ; ./tests.pl)
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js | tr "-" "_"`
                if [ "$GIT_BRANCH" = "origin/master" ]; then
                  fpm -s dir -t deb -n moloch -v $MOLOCH_VERSION --iteration $SD_BUILD_ID --template-scripts --after-install "release/afterinstall.sh" --url "http://molo.ch" --description "Moloch Full Packet System" -d libwww-perl -d libjson-perl -d ethtool -d libyaml-dev /data/moloch
                  aws s3 cp --quiet moloch*amd64.deb s3://files.molo.ch/moloch_master_ubuntu14_amd64.deb --acl public-read
                  aws s3api put-object-acl --bucket files.molo.ch --key moloch_master_ubuntu14_amd64.deb --acl public-read
                fi
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

    ubuntu-16:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-16:0.20.2
        steps:
            - ln -s /thirdparty .
            - build: ./easybutton-build.sh
            - export PATH=/data/moloch/bin:$PATH
            - installing: make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - test-capture: (cd tests ; ./tests.pl)
            - export TZ=US/Eastern
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js | tr "-" "_"`
                if [ "$GIT_BRANCH" = "origin/master" ]; then
                  fpm -s dir -t deb -n moloch -v $MOLOCH_VERSION --iteration $SD_BUILD_ID --template-scripts --after-install "release/afterinstall.sh" --url "http://molo.ch" --description "Moloch Full Packet System" -d libwww-perl -d libjson-perl -d ethtool -d libyaml-dev /data/moloch
                  aws s3 cp --quiet moloch*amd64.deb s3://files.molo.ch/moloch-master_ubuntu16_amd64.deb --acl public-read
                  aws s3api put-object-acl --bucket files.molo.ch --key moloch-master_ubuntu16_amd64.deb --acl public-read
                fi
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

    ubuntu-18:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-18:0.20.2
        steps:
            - ln -s /thirdparty .
            - build: ./easybutton-build.sh
            - export PATH=/data/moloch/bin:$PATH
            - installing: make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
# Doesn't seem to work on ubuntu-18 currently
#            - test-capture: (cd tests ; ./tests.pl)
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js | tr "-" "_"`
                if [ "$GIT_BRANCH" = "origin/master" ]; then
                  fpm -s dir -t deb -n moloch -v $MOLOCH_VERSION --iteration $SD_BUILD_ID --template-scripts --after-install "release/afterinstall.sh" --url "http://molo.ch" --description "Moloch Full Packet System" -d libwww-perl -d libjson-perl -d ethtool -d libyaml-dev /data/moloch
                  aws s3 cp --quiet moloch*amd64.deb s3://files.molo.ch/moloch-master_ubuntu18_amd64.deb --acl public-read
                  aws s3api put-object-acl --bucket files.molo.ch --key moloch-master_ubuntu18_amd64.deb --acl public-read
                fi
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY



    slack:
        requires: [centos-6, centos-7, ubuntu-14, ubuntu-16, ubuntu-18]
        image: andywick/moloch-build-7:6
        steps:
            - slack-success: |
                export MOLOCH_VERSION=`grep PACKAGE_VERSION= configure | sed "s/.*'\(.*\)\'.*$/\1/"`
                if [ "$GIT_BRANCH" = "origin/master" ]; then
                  BUILD_VERSION=`git describe --tags`
                  MSG=`git log -1 --format=%s`
                  BODY="{\"icon_emoji\": \":sushi:\", \"username\": \"MolochBuild\", \"text\":\"It worked: $GIT_BRANCH - moloch-$MOLOCH_VERSION-$SD_BUILD_ID - $MSG\"}"
                  curl -XPOST -H "Content-type: application/json" --data "$BODY" $SLACK
                fi
        secrets:
            - SLACK
